# Generated by Django 2.1.7 on 2019-11-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('another', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anothermodel',
            old_name='city',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='anothermodel',
            old_name='full_name',
            new_name='name',
        ),
    ]
